package app.responses;

public enum ErrorType {
    INVALID_PASSWORD,
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    BAD_REQUEST,
    ACCESS_DENIED,
    OBJECT_ALREADY_EXISTS,
    OBJECT_NOT_FOUND
}
